#!/usr/bin/env perl

use strict;
use warnings;
use 5.014;
no if $] >= 5.018000, warnings => qw(experimental::smartmatch);

my $command = $ARGV[0];
given ($command) {
    when('on') {
        my ($mac) = $ARGV[1];
        my $ip = $ARGV[1];
    }
    when('off') {
        my ($username,$ip) = ($ARGV[1],$ARGV[2]);
    }
    when('check') {
        my $ip = $ARGV[1];
    }
}